# .github/workflows/pr-push.yml
name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: index.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.GPC_W3C_TR_TOKEN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-privacy/2024OctDec/0020.html
          W3C_BUILD_OVERRIDE: |
             shortName: gpc
             specStatus: WD
